<?php

namespace Database\Seeders;

use App\Models\PembayaranItem;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DataSeeder extends Seeder
{

    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('ref_jenjangs')->insert([
            'kode' => 'B',
            'nama' => 'Pasca Sarjana',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('ref_jenjangs')->insert([
            'kode' => 'C',
            'nama' => 'Sarjana',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('ref_agamas')->insert([
            [
                'kode' => 'i',
                'nama' => 'Islam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'k',
                'nama' => 'Kristen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 't',
                'nama' => 'Katolik',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'h',
                'nama' => 'Hindu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'b',
                'nama' => 'Buddha',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => 'g',
                'nama' => 'Konghucu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);


        DB::table('perguruan_tinggis')->insert([
            'feeder_id' => Str::uuid(),
            'nama' => 'Universitas Contoh',
            'jalan' => 'Jl. Contoh No. 1, Kota Contoh',
            'telepon' => '021-12345678',
            'email' => 'info@universitascontoh.ac.id',
            'website' => 'https://www.universitascontoh.ac.id',
            // 'akreditasi' => 'A',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Seeder untuk tabel fakultas
        DB::table('fakultas')->insert([
            [
                'feeder_id' => Str::uuid(),
                'nama' => 'Fakultas Teknik',
                'perguruan_tinggi_id' => 1, // Asumsikan Universitas Contoh memiliki ID 1
                // 'telepon' => '021-12345679',
                // 'akreditasi' => 'A',
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feeder_id' => Str::uuid(),
                'nama' => 'Fakultas Ekonomi',
                'perguruan_tinggi_id' => 1, // Asumsikan Universitas Contoh memiliki ID 1
                // 'telepon' => '021-12345680',
                'status' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seeder untuk tabel prodi
        DB::table('prodis')->insert([
            [
                'feeder_id' => Str::uuid(),
                'kode' => 'TI',
                'nama' => 'Teknik Informatika',
                'fakultas_id' => 1, // Asumsikan Fakultas Teknik memiliki ID 1
                'perguruan_tinggi_id' => 1,
                'id_jenjang_pendidikan' => 1, // Asumsikan jenjang_id 1 adalah S1
                'telepon' => '021-12345681',
                'kaprodi_nama' => 'Kaprodi TI',
                'kaprodi_nidn' => 'NIDN0001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feeder_id' => Str::uuid(),
                'kode' => 'TE',
                'nama' => 'Teknik Elektro',
                'fakultas_id' => 1, // Asumsikan Fakultas Teknik memiliki ID 1
                'perguruan_tinggi_id' => 1,
                'id_jenjang_pendidikan' => 1, // Asumsikan jenjang_id 1 adalah S1
                'telepon' => '021-12345682',
                'kaprodi_nama' => 'Kaprodi TE',
                'kaprodi_nidn' => 'NIDN0002',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feeder_id' => Str::uuid(),
                'kode' => 'MA',
                'nama' => 'Manajemen',
                'fakultas_id' => 2, // Asumsikan Fakultas Ekonomi memiliki ID 2
                'perguruan_tinggi_id' => 1,
                'id_jenjang_pendidikan' => 1, // Asumsikan jenjang_id 1 adalah S1
                'telepon' => '021-12345683',
                'kaprodi_nama' => 'Kaprodi Manajemen',
                'kaprodi_nidn' => 'NIDN0003',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'feeder_id' => Str::uuid(),
                'kode' => 'AK',
                'nama' => 'Akuntansi',
                'fakultas_id' => 2, // Asumsikan Fakultas Ekonomi memiliki ID 2
                'perguruan_tinggi_id' => 1,
                'id_jenjang_pendidikan' => 1, // Asumsikan jenjang_id 1 adalah S1
                'telepon' => '021-12345684',
                'kaprodi_nama' => 'Kaprodi Akuntansi',
                'kaprodi_nidn' => 'NIDN0004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seeder untuk tabel kurikulum
        DB::table('kurikulums')->insert([
            [
                'prodi_id' => 1,
                'nama' => 'Kurikulum 2021',
                'keterangan' => 'Kurikulum 2021 Prodi Teknik Informatika',
                'jumlah_sks_lulus' => 144,
                'jumlah_sks_wajib' => 108,
                'jumlah_sks_pilihan' => 36,
                'jumlah_sks_pkl' => 0,
                'jumlah_sks_skripsi' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'nama' => 'Kurikulum 2024',
                'keterangan' => 'Kurikulum 2024 Prodi Teknik Informatika',
                'jumlah_sks_lulus' => 144,
                'jumlah_sks_wajib' => 108,
                'jumlah_sks_pilihan' => 36,
                'jumlah_sks_pkl' => 0,
                'jumlah_sks_skripsi' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'prodi_id' => 2,
                'nama' => 'Kurikulum 2021',
                'keterangan' => 'Kurikulum 2021 Prodi Teknik Elektro',
                'jumlah_sks_lulus' => 144,
                'jumlah_sks_wajib' => 108,
                'jumlah_sks_pilihan' => 36,
                'jumlah_sks_pkl' => 0,
                'jumlah_sks_skripsi' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Seeder untuk tabel matakuliah
        DB::table('matakuliahs')->insert([
            // Kurikulum 2021 Prodi Teknik Informatika
            [
                'prodi_id' => 1,
                'kurikulum_id' => 1,
                'kode' => 'MKP-101',
                'nama' => 'Pemrograman Dasar',
                'semester' => 1,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 1,
                'kode' => 'MKP-102',
                'nama' => 'Algoritma dan Pemrograman',
                'semester' => 1,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 1,
                'kode' => 'MKP-103',
                'nama' => 'Struktur Data',
                'semester' => 2,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 1,
                'kode' => 'MKP-104',
                'nama' => 'Basis Data',
                'semester' => 2,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 1,
                'kode' => 'MKP-105',
                'nama' => 'Pemrograman Web',
                'semester' => 3,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 1,
                'kode' => 'MKP-106',
                'nama' => 'Pemrograman Mobile',
                'semester' => 3,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_per
                        kuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 1,
                'kode' => 'MKP-107',
                'nama' => 'Pemrograman Game',
                'semester' => 4,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 1,
                'kode' => 'MKP-108',
                'nama' => 'Pemrograman Jaringan',
                'semester' => 4,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 1,
                'kode' => 'MKP-109',
                'nama' => 'Pemrograman Berbasis Objek',
                'semester' => 5,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kurikulum 2024 Prodi Teknik Informatika
            [
                'prodi_id' => 1,
                'kurikulum_id' => 2,
                'kode' => 'MKP-101',
                'nama' => 'Pemrograman Dasar',
                'semester' => 1,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 2,
                'kode' => 'MKP-102',
                'nama' => 'Algoritma dan Pemrograman',
                'semester' => 1,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 2,
                'kode' => 'MKP-103',
                'nama' => 'Struktur Data',
                'semester' => 2,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 2,
                'kode' => 'MKP-104',
                'nama' => 'Basis Data',
                'semester' => 2,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 2,
                'kode' => 'MKP-105',
                'nama' => 'Pemrograman Web',
                'semester' => 3,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 2,
                'kode' => 'MKP-106',
                'nama' => 'Pemrograman Mobile',
                'semester' => 3,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 2,
                'kode' => 'MKP-107',
                'nama' => 'Pemrograman Game',
                'semester' => 4,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 1,
                'kurikulum_id' => 2,
                'kode' => 'MKP-108',
                'nama' => 'Pemrograman Jaringan',
                'semester' => 4,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'A',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kurikulum 2021 Prodi Teknik Elektro
            [
                'prodi_id' => 2,
                'kurikulum_id' => 3,
                'kode' => 'MKE-101',
                'nama' => 'Elektronika Dasar',
                'semester' => 1,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'B',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 2,
                'kurikulum_id' => 3,
                'kode' => 'MKE-102',
                'nama' => 'Pengantar Teknik Elektro',
                'semester' => 1,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'B',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 2,
                'kurikulum_id' => 3,
                'kode' => 'MKE-103',
                'nama' => 'Pengantar Sistem Digital',
                'semester' => 2,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'B',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi
                        ' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 2,
                'kurikulum_id' => 3,
                'kode' => 'MKE-104',
                'nama' => 'Pengantar Sistem Kontrol',
                'semester' => 2,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'B',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 2,
                'kurikulum_id' => 3,
                'kode' => 'MKE-105',
                'nama' => 'Pengantar Sistem Tenaga Listrik',
                'semester' => 3,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'B',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 2,
                'kurikulum_id' => 3,
                'kode' => 'MKE-106',
                'nama' => 'Pengantar Sistem Komunikasi',
                'semester' => 3,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'B',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simul
                        asi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 2,
                'kurikulum_id' => 3,
                'kode' => 'MKE-107',
                'nama' => 'Pengantar Sistem Kendali',
                'semester' => 4,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'B',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'prodi_id' => 2,
                'kurikulum_id' => 3,
                'kode' => 'MKE-108',
                'nama' => 'Pengantar Sistem Mikroprosesor',
                'semester' => 4,
                'sks' => 4,
                'jenis_matakuliah' => 'A',
                'kelompok_matakuliah' => 'B',
                'sks_tatap_muka' => 2,
                'sks_praktek' => 0,
                'sks_praktek_lapangan' => 0,
                'sks_simulasi' => 2,
                'metode_perkuliahan' => 'Tatap Muka',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);

        // Seeder untuk tabel mahasiswa
        for ($i = 1; $i <= 4; $i++) { // Loop untuk setiap prodi
            for ($j = 1; $j <= 10; $j++) { // Maksimal 10 mahasiswa per prodi
                DB::table('mahasiswas')->insert([
                    'nama' => 'Mahasiswa ' . $j . ' Prodi ' . $i,
                    'prodi_id' => $i,
                    'agama_id' => rand(1, 5), // Asumsikan ada 5 agama dalam tabel ref_agamas
                    'nim' => 'NIM' . $i . str_pad($j, 4, '0', STR_PAD_LEFT),
                    'angkatan' => 2024,
                    'email' => 'mahasiswa' . $j . 'prodi' . $i . '@contoh.ac.id',
                    'tempat_lahir' => 'Kota ' . $j,
                    'tanggal_lahir' => now()->subYears(rand(18, 22))->format('Y-m-d'),
                    'handphone' => '081234567' . str_pad($j, 3, '0', STR_PAD_LEFT),
                    'alamat' => 'Alamat Mahasiswa ' . $j,
                    'nisn' => 'NISN' . str_pad($j, 4, '0', STR_PAD_LEFT),
                    'nik' => 'NIK' . str_pad($j, 4, '0', STR_PAD_LEFT),
                    'npwp' => 'NPWP' . str_pad($j, 4, '0', STR_PAD_LEFT),
                    'jenis_kelamin' => rand(0, 1) ? 'L' : 'P',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'kurikulum_id' => ($i == 1) ?  1 : null, // Asumsikan ada 2 kurikulum untuk setiap prodi   
                ]);
            }
        }

        // Seeder untuk tabel dosen
        for ($i = 1; $i <= 20; $i++) {
            DB::table('dosens')->insert([
                'feeder_id' => Str::uuid(),
                'nama_dosen' => 'Dosen ' . $i,
                'nidn' => 'NIDN' . str_pad($i, 4, '0', STR_PAD_LEFT),
                // 'nuptk' => 'NUPTK' . str_pad($i, 4, '0', STR_PAD_LEFT),
                // 'prodi_id' => rand(1, 4), // Random prodi_id antara 1 dan 4
                // 'handphone' => '081234567' . str_pad($i, 3, '0', STR_PAD_LEFT),
                // 'email' => 'dosen' . $i . '@contoh.ac.id',
                // 'alamat' => 'Alamat Dosen ' . $i,
                // 'gelar_depan' => 'Dr.',
                // 'gelar_belakang' => 'M.T.',
                // 'status' => 'Aktif',
                // 'jenis_kelamin' => rand(0, 1) ? 'L' : 'P',
                // 'tanggal_lahir' => now()->subYears(rand(30, 50))->format('Y-m-d'),
                // 'tempat_lahir' => 'Kota ' . $i,
                // 'foto' => 'foto' . $i . '.jpg',
                // 'agama_id' => rand(1, 5), // Asumsikan ada 5 agama dalam tabel ref_agamas
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $pembayaranitems = [
            // Prodi 1 dan angkatan 2022
            ['prodi_id' => 1, 'angkatan' => 2022, 'nama' => 'Pembayaran SPP', 'jumlah' => 3500000],
            ['prodi_id' => 1, 'angkatan' => 2022, 'nama' => 'Pembayaran UKT', 'jumlah' => 5000000],
            ['prodi_id' => 1, 'angkatan' => 2022, 'nama' => 'Pembayaran Praktikum', 'jumlah' => 1000000],
            ['prodi_id' => 1, 'angkatan' => 2022, 'nama' => 'Pembayaran Ujian', 'jumlah' => 500000],
            ['prodi_id' => 1, 'angkatan' => 2022, 'nama' => 'Pembayaran Wisuda', 'jumlah' => 1000000],
            ['prodi_id' => 1, 'angkatan' => 2022, 'nama' => 'Pembayaran KKN', 'jumlah' => 500000],
            ['prodi_id' => 1, 'angkatan' => 2022, 'nama' => 'Pembayaran Lainnya', 'jumlah' => 500000],
            // Prodi 1 dan angkatan 2023
            ['prodi_id' => 1, 'angkatan' => 2023, 'nama' => 'Pembayaran SPP', 'jumlah' => 3500000],
            ['prodi_id' => 1, 'angkatan' => 2023, 'nama' => 'Pembayaran UKT', 'jumlah' => 5000000],
            ['prodi_id' => 1, 'angkatan' => 2023, 'nama' => 'Pembayaran Praktikum', 'jumlah' => 1000000],
            ['prodi_id' => 1, 'angkatan' => 2023, 'nama' => 'Pembayaran Ujian', 'jumlah' => 500000],
            ['prodi_id' => 1, 'angkatan' => 2023, 'nama' => 'Pembayaran Wisuda', 'jumlah' => 1000000],
            ['prodi_id' => 1, 'angkatan' => 2023, 'nama' => 'Pembayaran KKN', 'jumlah' => 500000],
            ['prodi_id' => 1, 'angkatan' => 2023, 'nama' => 'Pembayaran Lainnya', 'jumlah' => 500000],
            // Prodi 1 dan angkatan 2024
            ['prodi_id' => 1, 'angkatan' => 2024, 'nama' => 'Pembayaran SPP', 'jumlah' => 3500000],
            ['prodi_id' => 1, 'angkatan' => 2024, 'nama' => 'Pembayaran UKT', 'jumlah' => 5000000],
            ['prodi_id' => 1, 'angkatan' => 2024, 'nama' => 'Pembayaran Praktikum', 'jumlah' => 1000000],
            ['prodi_id' => 1, 'angkatan' => 2024, 'nama' => 'Pembayaran Ujian', 'jumlah' => 500000],
            ['prodi_id' => 1, 'angkatan' => 2024, 'nama' => 'Pembayaran Wisuda', 'jumlah' => 1000000],
            ['prodi_id' => 1, 'angkatan' => 2024, 'nama' => 'Pembayaran KKN', 'jumlah' => 500000],
            ['prodi_id' => 1, 'angkatan' => 2024, 'nama' => 'Pembayaran Lainnya', 'jumlah' => 500000],
            // Prodi 2 dan angkatan 2025
            ['prodi_id' => 2, 'angkatan' => 2025, 'nama' => 'Pembayaran SPP', 'jumlah' => 3500000],
            ['prodi_id' => 2, 'angkatan' => 2025, 'nama' => 'Pembayaran UKT', 'jumlah' => 5000000],
            ['prodi_id' => 2, 'angkatan' => 2025, 'nama' => 'Pembayaran Praktikum', 'jumlah' => 1000000],
            ['prodi_id' => 2, 'angkatan' => 2025, 'nama' => 'Pembayaran Ujian', 'jumlah' => 500000],
            ['prodi_id' => 2, 'angkatan' => 2025, 'nama' => 'Pembayaran Wisuda', 'jumlah' => 1000000],
            ['prodi_id' => 2, 'angkatan' => 2025, 'nama' => 'Pembayaran KKN', 'jumlah' => 500000],
            ['prodi_id' => 2, 'angkatan' => 2025, 'nama' => 'Pembayaran Lainnya', 'jumlah' => 500000],
        ];

        foreach ($pembayaranitems as $pembayaranitem) {
            PembayaranItem::create($pembayaranitem);
        }
    }
}
